import { ArrowRight, CalendarDays, Check, Clock3, CreditCard, Home, LifeBuoy, Repeat2, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useGetEmployeeOverview, getGetEmployeeOverviewQueryKey } from "@workspace/api-client-react";
import { PlatformHeader, StatTile, DataState } from "@/components/platform-shell";
import { PlatformShell } from "@/components/platform-shell";

function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "AED", maximumFractionDigits: 0 }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(value)); }

export default function Employee() {
  const query = useGetEmployeeOverview({ query: { queryKey: getGetEmployeeOverviewQueryKey() } });
  const data = query.data;
  return <PlatformShell role="employee"><div className="mx-auto max-w-6xl">
    <PlatformHeader kicker="Your Loup benefit" title={data ? `Good morning, ${data.employeeName.split(" ")[0]}.` : "Your life, with a little more room."} description={data ? `${data.employerName} has set aside a private allowance for the things that keep your household moving.` : "Your private benefit concierge is loading."} action={<Link href="/browse" className="inline-flex items-center gap-2 rounded-full bg-foreground px-4 py-2.5 text-sm text-background transition-transform hover:-translate-y-0.5" data-testid="link-employee-browse">Browse services <ArrowRight className="h-4 w-4" /></Link>} />
    <DataState loading={query.isLoading} error={query.isError} onRetry={() => void query.refetch()}>
      {data && <div className="space-y-5">
        <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
          <div className="relative overflow-hidden rounded-3xl bg-foreground p-7 text-background sm:p-9"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[38px] border-primary/70 opacity-80" /><div className="relative"><p className="text-xs uppercase tracking-[0.18em] text-background/60">Available to use</p><div className="mt-3 flex flex-wrap items-baseline gap-3"><span className="font-serif text-6xl">{money(data.allowance.available)}</span><span className="text-sm text-background/65">of {money(data.allowance.authorized)} this cycle</span></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-background/15"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, (data.allowance.redeemed / data.allowance.authorized) * 100)}%` }} /></div><div className="mt-3 flex justify-between text-xs text-background/60"><span>{money(data.allowance.redeemed)} redeemed</span><span>Renews {date(data.allowance.renewalDate)}</span></div><Link href="/billing" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-background" data-testid="link-employee-allowance-details">See allowance details <ArrowRight className="h-4 w-4" /></Link></div></div>
          <div className="platform-surface rounded-3xl p-7"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Next on the calendar</p><CalendarDays className="h-5 w-5 text-primary" /></div>{data.upcomingBooking ? <><p className="mt-8 font-serif text-3xl">{data.upcomingBooking.serviceName}</p><p className="mt-2 text-sm text-muted-foreground">{data.upcomingBooking.providerName} · {date(data.upcomingBooking.scheduledAt)}</p><div className="mt-7 flex items-center gap-2 text-sm"><span className="h-2 w-2 rounded-full bg-primary" /> {data.upcomingBooking.status.replaceAll("_", " ")}</div><Link href={`/bookings/${data.upcomingBooking.id}`} className="mt-8 inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm hover:bg-accent" data-testid="link-employee-upcoming-booking">Open booking <ArrowRight className="h-4 w-4" /></Link></> : <div className="mt-8 rounded-2xl bg-accent/60 p-5"><p className="font-serif text-2xl">A calm calendar is a good calendar.</p><Link href="/browse" className="mt-4 inline-flex text-sm font-medium text-primary" data-testid="link-employee-empty-booking">Find a service <ArrowRight className="ml-1 h-4 w-4" /></Link></div>}</div>
        </section>
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatTile label="Time returned" value={`${Math.floor(data.metrics.estimatedTimeSavedMinutes / 60)}h ${data.metrics.estimatedTimeSavedMinutes % 60}m`} detail="estimated this year" tone="brass" /><StatTile label="Services completed" value={String(data.metrics.servicesCompleted)} detail="across your household" /><StatTile label="Employer support" value={money(data.metrics.employerSupport)} detail="contributed to your care" tone="mint" /><StatTile label="Household allocations" value={String(data.metrics.householdAllocations)} detail="shared with your pack" tone="plum" /></section>
        <section className="grid gap-5 lg:grid-cols-[1fr_.8fr]">
          <div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Eligible services</p><h2 className="mt-2 text-3xl">Make room for what matters.</h2></div><Sparkles className="h-5 w-5 text-primary" /></div><div className="mt-6 divide-y divide-border/70">{data.activeCategories.slice(0, 4).map((service) => <div key={service.slug} className="flex items-center gap-4 py-4" data-testid={`row-employee-service-${service.slug}`}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent"><Home className="h-4 w-4 text-primary" /></div><div className="min-w-0 flex-1"><p className="font-medium">{service.name}</p><p className="truncate text-xs text-muted-foreground">{service.description}</p></div><span className="text-sm font-medium">{money(service.employeeCopayment)}</span></div>)}</div><Link href="/browse" className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-primary" data-testid="link-employee-all-services">View all services <ArrowRight className="h-4 w-4" /></Link></div>
          <div className="platform-surface rounded-3xl p-6 sm:p-7"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Routines</p><h2 className="mt-2 text-3xl">Set it, then forget it.</h2><div className="mt-6 space-y-3">{data.routines.slice(0, 3).map((routine) => <div key={routine.id} className="rounded-2xl bg-accent/60 p-4" data-testid={`row-employee-routine-${routine.id}`}><div className="flex items-center gap-3"><Repeat2 className="h-4 w-4 text-primary" /><p className="font-medium">{routine.label}</p><span className="ml-auto text-xs text-primary">{routine.status}</span></div><p className="mt-2 pl-7 text-xs text-muted-foreground">{routine.frequency} · {routine.preferredDay}, {routine.preferredTime}</p></div>)}</div><Link href="/household" className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-primary" data-testid="link-employee-household">Manage household <ArrowRight className="h-4 w-4" /></Link></div>
        </section>
      </div>}
    </DataState>
    <div className="mt-7 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-primary" /> Benefit privacy protected</span><span className="inline-flex items-center gap-2"><Clock3 className="h-3.5 w-3.5 text-primary" /> Human support when needed</span><Link href="/support" className="inline-flex items-center gap-2 hover:text-foreground" data-testid="link-employee-support"><LifeBuoy className="h-3.5 w-3.5" /> Talk to Loup support</Link><Link href="/billing" className="inline-flex items-center gap-2 hover:text-foreground" data-testid="link-employee-billing"><CreditCard className="h-3.5 w-3.5" /> View billing</Link></div>
  </div></PlatformShell>;
}