import { useState } from "react";
import { ArrowUpRight, CheckCircle2, Download, FileSpreadsheet, Link2, Search, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useGetEmployerOverview, getGetEmployerOverviewQueryKey, useListEmployerEmployees, getListEmployerEmployeesQueryKey, useGetEmployerUtilization, getGetEmployerUtilizationQueryKey, useGetEmployerIntegrations, getGetEmployerIntegrationsQueryKey, useImportEmployerEmployees } from "@workspace/api-client-react";
import { DataState, PlatformHeader, PlatformShell, StatTile } from "@/components/platform-shell";

function percent(value: number) { return `${Math.round(value * 100)}%`; }
function percentagePoints(value: number) { return `${Math.round(value)}%`; }
function percentageWidth(value: number) { return `${Math.min(100, Math.max(0, value))}%`; }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "AED", maximumFractionDigits: 0 }).format(value); }

export default function Employer() {
  const [search, setSearch] = useState("");
  const [csv, setCsv] = useState("");
  const overview = useGetEmployerOverview({ query: { queryKey: getGetEmployerOverviewQueryKey() } });
  const employees = useListEmployerEmployees({ query: { queryKey: getListEmployerEmployeesQueryKey() } });
  const utilization = useGetEmployerUtilization({ query: { queryKey: getGetEmployerUtilizationQueryKey() } });
  const integrations = useGetEmployerIntegrations({ query: { queryKey: getGetEmployerIntegrationsQueryKey() } });
  const importer = useImportEmployerEmployees();
  const roster = employees.data?.filter((employee) => `${employee.name} ${employee.workEmail} ${employee.department}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const retry = () => { void overview.refetch(); void employees.refetch(); void utilization.refetch(); void integrations.refetch(); };
  return <PlatformShell role="employer"><PlatformHeader kicker="Benefits governance" title={overview.data?.employerName ?? "Employer workspace"} description="See whether the benefit is reaching people, where it is helping, and what the next operational decision should be." action={<button type="button" onClick={() => document.getElementById("import-roster")?.focus()} className="inline-flex items-center gap-2 rounded-full bg-foreground px-4 py-2.5 text-sm text-background hover:-translate-y-0.5 transition-transform" data-testid="button-employer-import-focus"><Download className="h-4 w-4" /> Import roster</button>} />
    <DataState loading={overview.isLoading} error={overview.isError} onRetry={retry}>{overview.data && <div className="space-y-5">
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatTile label="Activated employees" value={`${overview.data.activatedEmployees} / ${overview.data.eligibleEmployees}`} detail={`${percent(overview.data.activatedEmployees / overview.data.eligibleEmployees)} activation`} tone="brass" /><StatTile label="Forecast redemptions" value={money(overview.data.forecastRedemptions)} detail="next 30 days" /><StatTile label="Completion rate" value={percentagePoints(overview.data.completionRate)} detail={`${overview.data.satisfaction.toFixed(1)} / 5 satisfaction`} tone="mint" /><StatTile label="Invoice estimate" value={money(overview.data.invoiceEstimate)} detail="current cycle" tone="plum" /></section>
      <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
        <div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Benefit pulse</p><h2 className="mt-2 text-3xl">Adoption with a human read.</h2></div><ShieldCheck className="h-5 w-5 text-primary" /></div>{utilization.data ? <div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-accent/60 p-4"><p className="text-xs text-muted-foreground">Activation rate</p><p className="mt-2 font-serif text-3xl">{percentagePoints(utilization.data.activationRate)}</p><div className="mt-3 h-1.5 rounded-full bg-border"><div className="h-full rounded-full bg-primary" style={{ width: percentageWidth(utilization.data.activationRate) }} /></div></div><div className="rounded-2xl bg-accent/60 p-4"><p className="text-xs text-muted-foreground">Time returned</p><p className="mt-2 font-serif text-3xl">{Math.round(utilization.data.estimatedTimeSavedMinutes / 60)}h</p><p className="mt-1 text-xs text-muted-foreground">estimated across the roster</p></div><div className="rounded-2xl bg-accent/60 p-4"><p className="text-xs text-muted-foreground">Corporate savings</p><p className="mt-2 font-serif text-3xl">{money(utilization.data.corporateSavings)}</p><p className="mt-1 text-xs text-muted-foreground">versus unmanaged time cost</p></div><div className="rounded-2xl bg-accent/60 p-4"><p className="text-xs text-muted-foreground">Service recovery</p><p className="mt-2 font-serif text-3xl">{percentagePoints(utilization.data.serviceRecoveryRate)}</p><p className="mt-1 text-xs text-muted-foreground">issues resolved by Loup</p></div></div> : <div className="mt-7 h-32 animate-pulse rounded-2xl bg-muted/60" />}</div>
        <div className="platform-surface rounded-3xl p-6 sm:p-7"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Category mix</p><h2 className="mt-2 text-3xl">What people hand off.</h2><div className="mt-6 space-y-4">{utilization.data?.categoryUtilization.map((item) => <div key={item.category} data-testid={`row-utilization-${item.category}`}><div className="mb-1 flex justify-between text-sm"><span>{item.category}</span><span className="text-muted-foreground">{item.bookings} bookings</span></div><div className="h-2 rounded-full bg-accent"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(8, item.share * 100)}%` }} /></div></div>)}</div></div>
      </section>
      <section id="roster" className="platform-surface scroll-mt-24 rounded-3xl p-6 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">People covered</p><h2 className="mt-2 text-3xl">Roster</h2></div><label className="flex items-center gap-2 rounded-full border border-border bg-background/60 px-3 py-2 text-sm"><Search className="h-4 w-4 text-muted-foreground" /><span className="sr-only">Search employees</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search people" className="w-40 bg-transparent outline-none placeholder:text-muted-foreground" data-testid="input-employer-roster-search" /></label></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-[0.12em] text-muted-foreground"><th className="pb-3 font-medium">Employee</th><th className="pb-3 font-medium">Department</th><th className="pb-3 font-medium">Tier</th><th className="pb-3 font-medium">Eligibility</th><th className="pb-3 font-medium">Household</th></tr></thead><tbody>{roster.map((employee) => <tr key={employee.id} className="border-b border-border/60 last:border-0" data-testid={`row-employer-employee-${employee.id}`}><td className="py-4"><p className="font-medium">{employee.name}</p><p className="text-xs text-muted-foreground">{employee.workEmail}</p></td><td className="py-4 text-muted-foreground">{employee.department}</td><td className="py-4">{employee.benefitTier}</td><td className="py-4"><span className="inline-flex items-center gap-1.5 text-xs"><span className="h-1.5 w-1.5 rounded-full bg-primary" />{employee.eligibilityStatus}</span></td><td className="py-4 text-muted-foreground">{employee.householdEligible ? "Eligible" : "Employee only"}</td></tr>)}</tbody></table>{!employees.isLoading && !employees.isError && roster.length === 0 && <div className="p-8 text-center text-sm text-muted-foreground" data-testid="empty-employer-roster">No employees match that search.</div>}</div></section>
      <section id="integrations" className="grid scroll-mt-24 gap-5 lg:grid-cols-[1fr_1fr]"><div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-center gap-3"><Link2 className="h-5 w-5 text-primary" /><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Connected systems</p><h2 className="mt-1 text-2xl">Integration cues</h2></div></div><div className="mt-6 space-y-3"><div className="flex items-center justify-between rounded-2xl bg-accent/60 p-4"><span className="text-sm">{integrations.data?.ssoLabel ?? "SSO connection"}</span><span className="inline-flex items-center gap-1.5 text-xs text-primary"><CheckCircle2 className="h-3.5 w-3.5" /> Connected</span></div><div className="flex items-center justify-between rounded-2xl bg-accent/60 p-4"><span className="text-sm">Embedded employee widget</span><Link href="/embed/demo" className="text-xs font-medium text-primary" data-testid="link-employer-widget">Preview <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></Link></div></div></div><div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-center gap-3"><FileSpreadsheet className="h-5 w-5 text-primary" /><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Roster import</p><h2 className="mt-1 text-2xl">Bring people in.</h2></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Upload a CSV with work email, name, department, and benefit tier. This is a simulated import for the demo.</p><div className="mt-5 flex gap-2"><input id="import-roster" value={csv} onChange={(event) => setCsv(event.target.value)} placeholder="Paste CSV rows or a file name" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" data-testid="input-employer-csv" /><button type="button" disabled={!csv || importer.isPending} onClick={() => importer.mutate({ data: { csv } })} className="rounded-xl bg-foreground px-4 py-2 text-sm text-background disabled:cursor-not-allowed disabled:opacity-50" data-testid="button-employer-import">{importer.isPending ? "Importing…" : "Import"}</button></div>{importer.data && <p className="mt-3 text-xs text-primary" data-testid="status-employer-import">{importer.data.message}</p>}</div></section>
    </div>}</DataState>
  </PlatformShell>;
}