import { ArrowRight, BarChart3, CheckCircle2, MapPin, Radio, TrendingUp } from "lucide-react";
import { useGetVendorToday, getGetVendorTodayQueryKey, useGetVendorForecast, getGetVendorForecastQueryKey, useGetVendorPerformance, getGetVendorPerformanceQueryKey } from "@workspace/api-client-react";
import { DataState, PlatformHeader, PlatformShell, StatTile } from "@/components/platform-shell";

function time(value: string) { return new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
function percent(value: number) { return `${Math.round(value)}%`; }

export default function Vendor() {
  const today = useGetVendorToday({ query: { queryKey: getGetVendorTodayQueryKey() } });
  const forecast = useGetVendorForecast({ query: { queryKey: getGetVendorForecastQueryKey() } });
  const performance = useGetVendorPerformance({ query: { queryKey: getGetVendorPerformanceQueryKey() } });
  const retry = () => { void today.refetch(); void forecast.refetch(); void performance.refetch(); };
  return <PlatformShell role="vendor"><PlatformHeader kicker="Service operations" title={today.data?.vendorName ?? "Vendor workspace"} description="Your day, in one clear line of sight: the work accepted, the capacity left, and the moments that need a human decision." action={<span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-2.5 text-sm text-primary"><Radio className="h-4 w-4" /> Live demo feed</span>} />
    <DataState loading={today.isLoading} error={today.isError} onRetry={retry}>{today.data && <div className="space-y-5">
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatTile label="Assigned today" value={String(today.data.assignedBookings.length)} detail={`${today.data.awaitingAcceptance} awaiting acceptance`} tone="mint" /><StatTile label="Available capacity" value={String(today.data.availableCapacity)} detail="bookings remaining" /><StatTile label="Capacity warnings" value={String(today.data.capacityWarnings)} detail="needs review" tone="brass" /><StatTile label="Late arrival warnings" value={String(today.data.lateArrivalWarnings)} detail={`${today.data.serviceRecoveryActions} recovery actions`} tone="plum" /></section>
      <section className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">The run of show</p><h2 className="mt-2 text-3xl">Today’s bookings</h2></div><span className="text-xs text-muted-foreground">{today.data.assignedBookings.length} stops</span></div><div className="mt-7 space-y-3">{today.data.assignedBookings.map((booking) => <div key={booking.id} className="group flex flex-col gap-4 rounded-2xl border border-border/70 bg-background/50 p-4 transition-colors hover:border-primary/50 sm:flex-row sm:items-center" data-testid={`row-vendor-booking-${booking.id}`}><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent font-serif text-lg">{time(booking.scheduledAt).replace(" ", "")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{booking.category}</p><span className="rounded-full bg-accent px-2 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">{booking.status}</span></div><p className="mt-1 text-xs text-muted-foreground"><MapPin className="mr-1 inline h-3.5 w-3.5" />{booking.zone} · {booking.operationalRequirement}</p></div><button type="button" onClick={() => window.alert(`Booking ${booking.id} details are simulated.`)} className="inline-flex items-center justify-center gap-2 rounded-full border border-border px-3 py-2 text-xs font-medium hover:bg-accent" data-testid={`button-vendor-booking-${booking.id}`}>Review <ArrowRight className="h-3.5 w-3.5" /></button></div>)}</div>{today.data.assignedBookings.length === 0 && <div className="mt-6 rounded-2xl bg-accent/50 p-8 text-center" data-testid="empty-vendor-bookings"><p className="font-serif text-2xl">A clear day ahead.</p><p className="mt-2 text-sm text-muted-foreground">New assignments will appear here.</p></div>}</section>
      <section id="forecast" className="grid scroll-mt-24 gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-center gap-3"><TrendingUp className="h-5 w-5 text-primary" /><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Capacity forecast</p><h2 className="mt-1 text-2xl">Plan the next windows.</h2></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[590px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-[0.12em] text-muted-foreground"><th className="pb-3 font-medium">Window</th><th className="pb-3 font-medium">Demand</th><th className="pb-3 font-medium">Gap</th><th className="pb-3 font-medium">Recommendation</th></tr></thead><tbody>{forecast.data?.windows.map((window) => <tr key={`${window.label}-${window.zone}`} className="border-b border-border/60 last:border-0" data-testid={`row-vendor-forecast-${window.label}`}><td className="py-4"><p className="font-medium">{window.label}</p><p className="text-xs text-muted-foreground">{window.category} · {window.zone}</p></td><td className="py-4">{window.low}–{window.high}</td><td className="py-4"><span className={window.capacityGap > 0 ? "text-destructive" : "text-primary"}>{window.capacityGap > 0 ? `+${window.capacityGap}` : "Covered"}</span></td><td className="py-4 text-xs text-muted-foreground">{window.recommendation}</td></tr>)}</tbody></table></div></div><div className="platform-surface rounded-3xl p-6 sm:p-7"><div className="flex items-center gap-3"><BarChart3 className="h-5 w-5 text-primary" /><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Performance</p><h2 className="mt-1 text-2xl">Trust, measured.</h2></div></div>{performance.data && <div className="mt-6 space-y-5"><div className="flex items-end justify-between"><span className="text-sm text-muted-foreground">Completion</span><span className="font-serif text-3xl">{percent(performance.data.completionRate)}</span></div><div className="h-2 rounded-full bg-accent"><div className="h-full rounded-full bg-primary" style={{ width: `${performance.data.completionRate * 100}%` }} /></div><div className="grid grid-cols-2 gap-3">{[["On time", percent(performance.data.onTimeRate)], ["Rating", `${performance.data.averageRating.toFixed(1)} / 5`], ["Complaints", percent(performance.data.complaintRate)], ["Capacity accuracy", percent(performance.data.capacityAccuracy)]].map(([label, value]) => <div key={label} className="rounded-2xl bg-accent/60 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div></div>}</div></section>
      <section id="performance" className="scroll-mt-24 rounded-3xl bg-foreground p-6 text-background sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-background/55">Quality cue</p><h2 className="mt-2 font-serif text-3xl">Good service leaves a trace.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-background/65">Loup combines completion, timeliness, and recovery—not just volume—to help teams understand the relationship they are building with households.</p></div><div className="flex shrink-0 items-center gap-2 rounded-full bg-background/10 px-4 py-2 text-sm"><CheckCircle2 className="h-4 w-4 text-primary" /> Quality loop active</div></div></section>
    </div>}</DataState>
  </PlatformShell>;
}