// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/loup-home/ConciergeDesk.tsx": () => import("../components/mockups/loup-home/ConciergeDesk.tsx"),
  "./components/mockups/loup-home/GoldenHour.tsx": () => import("../components/mockups/loup-home/GoldenHour.tsx"),
  "./components/mockups/loup-home/HouseholdConsole.tsx": () => import("../components/mockups/loup-home/HouseholdConsole.tsx"),
  "./components/mockups/loup-home/MemberLens.tsx": () => import("../components/mockups/loup-home/MemberLens.tsx"),
  "./components/mockups/loup-home/PackConsole.tsx": () => import("../components/mockups/loup-home/PackConsole.tsx")
};
